#pragma once
#include <type_traits>

#include "atlas/core/ids.h"
#include "atlas/core/types.h"

namespace atlas {

// architecture-design.md §10 — the transaction scope is RAII and rolls back when the guard unwinds.
// The ledger carries the state so that a `Guarded` failure can tell "nothing was open" apart from
// "a transaction was open and must be rolled back".
enum class TxState : UInt8 { None, Active, Committed, RolledBack };

// architecture-design.md §10.4 — the idempotency key of the request currently being served,
// generated by the sender.
//
// 🔴 Strong-typed rather than a bare `UInt64` because the ledger now carries TWO 64-bit values that
// are only ever generated and compared (`trace_id` and this one). That is precisely the swap
// cpp-style.md §4.3 exists to stop, and it is the reason the note on `trace_id` below no longer
// holds on its own.
//
// 🔴 Deliberately NOT in core/ids.h. That header holds the identities of *entities* — account,
// character, session, actor — and `IdValue`'s concept enumerates exactly those four. A request
// de-duplication token is not an entity; widening the concept to admit it would let the ledger's
// bookkeeping launder through the entity extractor, which is the one thing that function exists to
// prevent.
enum class RequestKey : UInt64 {};

constexpr UInt64 RequestKeyValue(RequestKey key) noexcept { return static_cast<UInt64>(key); }

// architecture-design.md §10.4 — the request state machine, one step per durable fact:
//
//     None -> Received -> Persisted -> Responded
//
// `Received` means "this server owns the key and is executing"; `Persisted` means "the transaction
// COMMITTED and the result is recorded"; `Responded` means "the client was told". 🔴 The ordering
// is the contract, not a description: a step may be resumed from, never skipped. Persisted is
// unreachable before the commit, which is what makes "the response never precedes the commit" a
// structural fact rather than a convention (see db/idempotency.h).
enum class RequestState : UInt8 { None, Received, Persisted, Responded };

// architecture-design.md §9.2 — the ctx ledger.
//
// Built at the request entry point and carried across every thread boundary unchanged. Everything
// that has to appear in a log line or an exception message without being threaded through every
// signature lives here.
//
// `trace_id` is intentionally a plain `UInt64` rather than a strong-typed ID: it is generated and
// compared, and it is the only unwrapped 64-bit field here — `request_key`, the one field that
// could be confused with it, is strong-typed for exactly that reason.
struct Ctx {
    UInt64 trace_id{0};
    // Value-initialised rather than `{0}`: MSVC rejects the integer literal in a default member
    // initialiser for a scoped enumeration, and `{}` says "unset" more directly anyway.
    AccountId account_id{};
    CharacterId character_id{};
    SessionId session_id{};
    RequestKey request_key{};
    TxState tx_state{TxState::None};
    RequestState request_state{RequestState::None};
};

// 🔴 architecture-design.md §9.2 — the ledger crosses every thread boundary BY VALUE, so adding a
// field is a decision about copy cost and not only about content. Both properties that make the
// copy cheap are pinned here instead of assumed:
//
//   * trivially copyable — the copy is a memcpy with no destructor and no allocation, which is what
//     lets `Guarded` and `DbRunner::Submit` take a `Ctx` by value without thinking about it;
//   * one cache line — a hop that touches two lines costs more than the fields are worth.
//
// A field that breaks either line (a `std::string`, an owning handle) has to argue against these
// two assertions first. That argument is the point of them being here.
static_assert(std::is_trivially_copyable_v<Ctx>,
              "Ctx is copied across every thread boundary; keep the copy a memcpy");
static_assert(sizeof(Ctx) <= 64, "Ctx is copied on every thread hop; keep it within a cache line");

// The ledger installed on the calling thread right now. Never null; an unset ledger is a
// default-constructed `Ctx`.
const Ctx& CurrentCtx() noexcept;

// 🔴 architecture-design.md §9.2 — a plain `thread_local` is NOT enough.
//
// A strand serialises handlers but does not pin them to a thread, so the executing thread changes
// from handler to handler. The storage may be thread_local, but correctness comes from installing
// on entry and restoring on exit — which is exactly what this RAII scope does. `Guarded`
// (core/error.h) is the handler-boundary user of it; nesting works because each scope restores the
// exact value it displaced.
class CtxScope {
public:
    explicit CtxScope(const Ctx& ctx) noexcept;
    ~CtxScope();

    CtxScope(const CtxScope&) = delete;
    CtxScope& operator=(const CtxScope&) = delete;
    CtxScope(CtxScope&&) = delete;
    CtxScope& operator=(CtxScope&&) = delete;

private:
    Ctx previous_;
};

}  // namespace atlas
